Unemployment is measured by the unemployment rate which is the number of people
who are unemployed as a percentage of the total labour force. We have seen a sharp
increase in the unemployment rate during Covid-19, so analyzing the unemployment rate
can be a good data science project.

In [2]:
pip install pandas scikit-learn matplotlib seaborn jupyter

Requirement already satisfied: pandas in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (1.7.2)
Requirement already satisfied: matplotlib in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (3.10.9)
Requirement already satisfied: seaborn in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (0.13.2)
Requirement already satisfied: jupyter in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (1.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: pytz>=2020.1 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: scipy>=1.8.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: pyparsing>=3 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pillow>=8 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: packaging>=20.0 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from matplotlib) (26.2)
Requirement already satisfied: nbconvert in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (7.17.1)
Requirement already satisfied: jupyterlab in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (4.5.7)
Requirement already satisfied: notebook in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (7.5.6)
Requirement already satisfied: jupyter-console in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: ipywidgets in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter) (8.1.8)
Requirement already satisfied: ipykernel in c:\users\tisha\appdata\roaming\python\python310\site-packages (from jupyter) (7.2.0)
Requirement already satisfied: six>=1.5 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: pyzmq>=25 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter) (27.1.0)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter) (5.15.0)
Requirement already satisfied: comm>=0.1.1 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter) (0.2.3)
Requirement already satisfied: jupyter-client>=8.8.0 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter) (8.8.0)
Requirement already satisfied: psutil>=5.7 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter) (7.2.2)
Requirement already satisfied: tornado>=6.4.1 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter) (6.5.5)
Requirement already satisfied: ipython>=7.23.1 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter) (8.39.0)
Requirement already satisfied: nest-asyncio>=1.4 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter) (1.8.20)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter) (0.2.2)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter) (5.9.1)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets->jupyter) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets->jupyter) (3.0.16)
Requirement already satisfied: prompt-toolkit>=3.0.30 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from jupyter-console->jupyter) (3.0.52)
Requirement already satisfied: pygments in c:\users\tisha\appdata\roaming\python\python310\site-packages (from jupyter-console->jupyter) (2.20.0)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: setuptools>=41.1.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab->jupyter) (65.5.0)
Requirement already satisfied: httpx<1,>=0.25.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab->jupyter) (2.18.2)
Requirement already satisfied: tomli>=1.2.2 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab->jupyter) (2.4.1)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab->jupyter) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab->jupyter) (2.3.0)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab->jupyter) (2.3.1)
Requirement already satisfied: bleach[css]!=5.0.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->jupyter) (6.3.0)
Requirement already satisfied: markupsafe>=2.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->jupyter) (3.0.3)
Requirement already satisfied: nbformat>=5.7 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->jupyter) (5.10.4)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->jupyter) (3.2.1)
Requirement already satisfied: beautifulsoup4 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->jupyter) (4.14.3)
Requirement already satisfied: jupyterlab-pygments in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->jupyter) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: defusedxml in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: typing_extensions>=4.0.0 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from async-lru>=1.0.0->jupyterlab->jupyter) (4.15.0)
Requirement already satisfied: webencodings in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.4.0)
Requirement already satisfied: certifi in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (2026.5.20)
Requirement already satisfied: httpcore==1.* in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: anyio in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.13.0)
Requirement already satisfied: idna in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (3.15)
Requirement already satisfied: h11>=0.16 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Requirement already satisfied: jedi>=0.16 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.20.0)
Requirement already satisfied: decorator in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.3.1)
Requirement already satisfied: colorama in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.4.6)
Requirement already satisfied: stack_data in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: exceptiongroup in c:\users\tisha\appdata\roaming\python\python310\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (1.3.1)
Requirement already satisfied: platformdirs>=2.5 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel->jupyter) (4.9.6)
Requirement already satisfied: terminado>=0.8.3 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.12.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0.3)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.25.0)
Requirement already satisfied: overrides>=5.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (7.7.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.5.4)
Requirement already satisfied: websocket-client>=1.7 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.9.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.14.0)
Requirement already satisfied: babel>=2.10 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.18.0)
Requirement already satisfied: requests>=2.31 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.34.2)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (4.26.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from nbformat>=5.7->nbconvert->jupyter) (2.21.2)
Requirement already satisfied: wcwidth in c:\users\tisha\appdata\roaming\python\python310\site-packages (from prompt-toolkit>=3.0.30->jupyter-console->jupyter) (0.7.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.8.3)
Requirement already satisfied: argon2-cffi-bindings in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter) (0.8.7)
Requirement already satisfied: referencing>=0.28.4 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.37.0)
Requirement already satisfied: attrs>=22.2.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2025.9.1)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.30.0)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (6.0.3)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: rfc3339-validator in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.7.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from stack_data->ipython>=7.23.1->ipykernel->jupyter) (2.2.1)
Requirement already satisfied: pure-eval in c:\users\tisha\appdata\roaming\python\python310\site-packages (from stack_data->ipython>=7.23.1->ipykernel->jupyter) (0.2.3)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\tisha\appdata\roaming\python\python310\site-packages (from stack_data->ipython>=7.23.1->ipykernel->jupyter) (3.0.1)
Requirement already satisfied: isoduration in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (25.10.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (1.1.0)
Requirement already satisfied: fqdn in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: uri-template in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.0)
Requirement already satisfied: pycparser in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0)
Requirement already satisfied: lark>=1.2.2 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from rfc3987-syntax>=1.1.0->jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: arrow>=0.15.0 in c:\users\tisha\appdata\local\programs\python\python310\lib\site-packages (from isoduration->jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (1.4.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [4]:
data = pd.read_csv("Unemployment in India.csv")

data.head()

,Region,Date,Frequency,Estimated Unemployment Rate (%),Estimated Employed,Estimated Labour Participation Rate (%),Area
0,Andhra Pradesh,31-05-2019,Monthly,3.65,11999139.0,43.24,Rural
1,Andhra Pradesh,30-06-2019,Monthly,3.05,11755881.0,42.05,Rural
2,Andhra Pradesh,31-07-2019,Monthly,3.75,12086707.0,43.50,Rural
3,Andhra Pradesh,31-08-2019,Monthly,3.32,12285693.0,43.97,Rural
4,Andhra Pradesh,30-09-2019,Monthly,5.17,12256762.0,44.68,Rural

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 7 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Region                                    740 non-null    object
 1    Date                                     740 non-null    object
 2    Frequency                                740 non-null    object
 3    Estimated Unemployment Rate (%)          740 non-null    float64
 4    Estimated Employed                       740 non-null    float64
 5    Estimated Labour Participation Rate (%)  740 non-null    float64
 6   Area                                      740 non-null    object
dtypes: float64(3), object(4)
memory usage: 42.1+ KB

In [6]:
data.describe()

,Estimated Unemployment Rate (%),Estimated Employed,Estimated Labour Participation Rate (%)
count,740.000000,7.400000e+02,740.000000
mean,11.787946,7.204460e+06,42.630122
std,10.721298,8.087988e+06,8.111094
min,0.000000,4.942000e+04,13.330000
25%,4.657500,1.190404e+06,38.062500
50%,8.350000,4.744178e+06,41.160000
75%,15.887500,1.127549e+07,45.505000
max,76.740000,4.577751e+07,72.570000

In [7]:
print(data.columns)

Index(['Region', ' Date', ' Frequency', ' Estimated Unemployment Rate (%)',
       ' Estimated Employed', ' Estimated Labour Participation Rate (%)',
       'Area'],
      dtype='object')

In [ ]:
print(data['Area'].unique())

['Rural' nan 'Urban']

: